index.js, index.test.js, package.json
Added a list of zero-decimal currencies
=> Add list of zero-decimal currencies

package.json, region-data.js
Add Stripe payment method to all regions
=> Add Stripe payment method to all regions

index.js, region-data.js
=> feat: add phone prefix

__mocks__/currency-data.js, currency-data.js, index.test.js
This PR takes care of adding Qantas as a payment method for Australia
=> feat: add qantas to payment methodes

currency-data.js, region-data.js
https://aussiecommerce.atlassian.net/browse/LENG-830
New regions we are targetting for mastercard partnership!!
=> Add new regions

region-data.js
Once we have mailing address I can remove this hardcoded stuff from https://github.com/brandsExclusive/svc-sailthru/blob/master/src/api/travel/lib/contact.js
=> Add region specific mailing address

index.js
Will do a major version release
=> Remove deprecated function

__mocks__/currency-data.js, __mocks__/flag-data.js, __mocks__/region-data.js, flag-data.js, index.js, index.test.js, region-data.js
=> feat: add getRegionFlagUrlsByCode

index.js, index.test.js, package.json
@forkfork @nguyenchr @eddiemcleanlux
=> add isRegionAllowed

region-data.js
https://aussiecommerce.atlassian.net/browse/ST-67
=> fix: scoopon phone number

package.json, region-data.js
=> add scooponexperience region data

currency-data.js
=> add scooponexperience currency list

region-data.js
=> hack in local number to international

region-data.js
* india
* hong kong
* singapore
=> Update singapore mailing address for

currency-data.js, region-data.js
Add new brands to lib regions to prevent errors on FB login
=> Add new brands to lib regions

currency-data.js, region-data.js
Reverts brandsExclusive/lib-regions#46
=> Revert "Add new brands to lib regions"

__mocks__/currency-data.js, __mocks__/region-data.js, index.js, index.test.js, region-data.js
Probably a minor version change as this is backwards compatible with all existing brands which default to the Australian market. In the case of treatme, not only does it not default to Australia, it doesn't serve Australia at all. In this case, it doesn't make sense for any defaults to Australia.
=> feat: default should be consistent with the brand

package.json, region-data.js
updates hong kong and Spanish numbers
=> [LENG-1097]

region-data.js
https://aussiecommerce.atlassian.net/browse/ST-303
=> fix deals treatme and cudo travel numbers

region-data.js
cdt travel on apps are showing scoopon numbers
=> use travel numbers in experiences

lib/flights.js, lib/flights.test.js
Get airport by code. Used by frontend
=> Allow to get airport by code

index.js, package.json
#78 did not include export by mistake
=> Fix export

lib/countries.js
=> Remove random character

__mocks__/region-data.js, index.js, index.test.js, region-data.js
https://aussiecommerce.atlassian.net/browse/LENG-1524
Canada: CAD50 (53.16AUD) 
China: CNY240 (50.18AUD)
France: EUR30 (47.81AUD) 
Germany: EUR30 (47.81AUD) 
Hong Kong: HKD300 (53.44AUD) 
India: INR2,500 (48.83AUD) 
Indonesia: IDR500,000 (50.23AUD) 
Ireland: EUR30 (47.81AUD) 
Israel: ILS130 (50.36AUD) 
Italy: EUR30 (47.81AUD) 
Japan: JPY4,000 (50.91AUD) 
Korea: KRW40,000 (49.93AUD) 
Macau: MOP300 (51.85) 
Malaysia: MYR150 (51.42AUD) 
New Zealand: NZD50 (48.03AUD) 
Philippines: PHP2,000 (53.46AUD) 
Qatar: QAR130 (49.91AUD) 
Russia: RUB2500 (53.30AUD) 
Saudi Arabia: SAR130 (48.46AUD) 
Singapore: SGD50 (51.68AUD) 
South Africa: ZAR500* (52.15AUD) 
Spain: EUR30 (47.81AUD) 
Taiwan: TWD1,000 (45.32AUD) 
Thailand: THB1,000 (44.71AUD) 
United Arab Emirates: AED130 (49.47AUD) 
United Kingdom: …
=> [LENG-1524] Added referral fee to regions

region-data.js
=> Added referral min spend

lib/flights.js, lib/flights.test.js
As the title suggests, add the latitude and longitude to the airport data
=> ST-717 - Add lat/long to airports

region-data.js
Add gift card amount options for AU. 
This data was currently in the customer portal but since we will add similar data for all regions it makes sense to be in the regions data.
=> Add gift card amount options for AU

region-data.js
https://aussiecommerce.atlassian.net/browse/LENG-1588
Removing all amount options above $1000 due to legal obligations
=> [LENG-1588] Remove some giftcard amount options

.gitignore, region-data.js
https://aussiecommerce.atlassian.net/browse/LENG-1573
=> add multicurrency for gift card

lib/flights.js
Add GOA and JOG and restore the destination sort that was accidentally removed last PR
=> Add new destinations and restore sort by name

currency-data.js
Add Kris flyer as a payment method for `SG, CN, TH, PH, ID, MY, VN, JP, KR, TW, NZ, UK, US, HK`
=> [LENG-1478] add kris flyer to available countries

package.json, src/regions.ts
https://aussiecommerce.atlassian.net/browse/LENG-1841
=> [LENG-1841] Update Regions API

src/index.test.ts, src/regions.ts
USA and Canada will have $ 50 refferal amount rather than $ 100.
=> [KAN-549] Updating Referral Amount For US and Canada

src/currencies.ts, src/index.test.ts
i assume it won't break because customer portal doesn't know about klarna...?
=> add klarna payment method to le au

src/regions.ts
https://aussiecommerce.atlassian.net/browse/KAN-813?atlOrigin=eyJpIjoiYjNiOWVmZmU1YjM4NDZhMmEzNWE4MWMxYzgzZjlhN2QiLCJwIjoiaiJ9
The old phone number has been disconnected... Replace it with the new number.
=> [KAN-813] Update disconnected phone number

package.json
Yarn publish failed to bump version so create a pr for this :-|
https://github.com/lux-group/lib-regions/pull/154
=> Bump version to v4.4.5

package.json, src/regions.ts
https://aussiecommerce.atlassian.net/browse/KAN-781?atlOrigin=eyJpIjoiNmUxMTg5ZjFiYzI2NDdlOGI2Y2I1NDk4ZmM4ZGJiOGMiLCJwIjoiaiJ9
Update local phone number only for /ae site.
=> [KAN-781] Update /ae local phone number

src/regions.ts
[Ticket](https://aussiecommerce.atlassian.net/browse/KAN-1171)
Update Italy and Ireland sales and support phone numbers.
=> KAN-1171 Update IT and IE local phone number

package.json, src/currencies.ts, src/index.test.ts
Changes for the following story:
https://aussiecommerce.atlassian.net/browse/PP-66
All tests passing.
=> Added bridgerPay for AUD payments

src/regions.ts
This PR updates the Indian support number
=> [TBB-227]: Update the Indian support number

src/regions.ts
We're moving away from Delacon and the numbers provided by them. Replacing the regions numbers down below with the international one.
=> Update some numbers as we move away from Delacon

src/regions.ts
https://aussiecommerce.atlassian.net/browse/OPEX-106
Change default mailing address
=> [OPEX-106] Update address in email footer

package.json
Fix missing updates on previous issued `yarn publish`
4.6.8 -> 4.6.9
=> Fix version after issued prev

package.json
https://aussiecommerce.atlassian.net/browse/OPEX-176
Bump version to 4.8.0
https://github.com/lux-group/lib-regions/pull/177
=> version 4.8.0

src/currencies.ts, src/index.test.ts
enable google pay as of the payment option for aud currency
=> add googlepay as one of the payment method for aud

package.json
Bump latest version to `4.8.1`
=> [OPEX-176] Bump version

package.json, src/regions.ts
https://gist.github.com/michael-malarchuk/6b98c568e992b39f5ccc913bb6db3669
Fix Netherlands configuration
=> [OPEX-176] Fix Netherlands Flag and currency formatter locale

package.json, src/currencies.ts
Another issue same as yesterday: https://sentry.io/organizations/luxury-escapes-9m/issues/2658351531/?environment=production&project=1488479&query=is%3Aunresolved&statsPeriod=1h
=> Disable apple and google pay in SA

package.json, src/currencies.ts, src/index.test.ts
https://aussiecommerce.atlassian.net/browse/PP-265
Added new payment method for accordion tile for Hoolah on the payment page
=> currency added

src/regions.ts
https://luxgroup-hq.slack.com/archives/CFJDMH4HZ/p1639455499205600
=> Update US phone number

package.json, src/regions.ts
https://luxgroup-hq.slack.com/archives/CFJDMH4HZ/p1639610758231200?thread_ts=1639455499.205600&cid=CFJDMH4HZ
=> Update UK phone number

package.json, src/index.ts, src/priorityPhoneNumbers.ts
[Ticket](https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-310)
https://github.com/lux-group/lib-uri-templates/pull/151
https://github.com/lux-group/svc-discovery/pull/252
https://github.com/lux-group/svc-graphql/pull/193
https://github.com/lux-group/lib-types/pull/313
We are providing priority phone numbers for high value orders, I'm adding those similar to regions array but in a separate module to exclude any issues. I declared new api endpoint in lib-uri-templates it will be used by svc-discovery to serve data for svc-graphql.
=> [OPE-310] add priority phone numbers

package.json, src/index.test.ts, src/regions.ts
Rolling back default region from the lib.
There is way too many dependencies on it - I just changed the redirect rules directly in customer portal instead.
=> DEVX-78: Reverting default region to AU

package.json, src/regions.ts
https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106
We updating some counties Sales & Support numbers.
WIP because not formatted yet
https://github.com/lux-group/svc-discovery/pull/253
=> [OPEX-552] update sales and support phone numbers WIP

package.json, src/regions.ts
FIX: previously changed China phone in wrong brand.
=> [OPEX-552] fix number for china, previously added in wrong brand

package.json, src/currencies.ts, src/index.test.ts
=> market added for atome

package.json, src/regions.ts
Add warning to old referral types
=> Deprecate old referral fields

src/regions.ts
[Link](https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-646)
=> OPEX-646 update international phone numbers

package.json, src/regions.ts
JIRA: [Link](https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-652)
Macau | provisioned - tested successfully | 6857 0524
Italy | provisioned - tested successfully | 800 684 328
=> OPEX-652 update local numbers for Macau and Italy

README.md
I personally found it pretty confusing just by reading the README to know what to do as a first time user, who has also never published anything to Node
It was also confusing to know if I *should* publish or not
=> Update README.md to be more prescriptive

package.json, src/regions.ts
Updated due to scope creep
[ticket](https://aussiecommerce.atlassian.net/browse/OPEX-686)
=> OPEX-686 update SK and France numbers

package.json, src/currencies.ts, src/index.test.ts, src/regions.ts
Adding intitial values for new kogantravel brand, needed to run Customer Portal with new brand in development
=> WLT-379 - Adding basic config for new KoganTravel brand

package.json, src/regions.ts
[JIRA](https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-709)
Update the Sales & Support phone numbers for the below
Qatar: 00 800 101636
Netherlands: 0800 2300300
=> OPEX-709 update qatar and netherlands phone numbers

src/regions.ts
https://aussiecommerce.atlassian.net/browse/OPEX-712
=> Update japan number

package.json, src/regions.ts
JIRA: [https://aussiecommerce.atlassian.net/browse/CONTB-819](https://aussiecommerce.atlassian.net/browse/CONTB-819)
=> feat(inclusions): [CONTB-819] Set the default LPC marketed LOS under the property

src/regions.ts
https://aussiecommerce.atlassian.net/browse/OPEX-754?focusedCommentId=115506&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-115506
=> Update South Africa phone number

package.json, src/index.ts, src/priorityPhoneNumbers.ts
fixed crash  when brand is missing from brand definition TS file.
=> Fixed priorityPhoneNumbers case where brand is not defined

package.json
=> Npm version 4 10 34

package.json
Bump up lib-regions to incorporate changes in #248 and #247
=> WLT-416 Bump up version

package.json
Bump up the version after said change in #250
=> WLT-416 Bump up the library version

package.json
Bump up the version after changes made in #256
=> WLT-612 Bump version number

src/extended.ts, src/index.test.ts, src/index.ts, src/regions.ts
Make the brand parameter accept only LE brands and not just any string.
Current state:
Improvement:
=> ENGX - Add types to brand names

package.json
Follow up for #259. Bump up the version number.
=> WLT-621 Bump up version number

package.json, src/currencies.ts, src/index.test.ts, src/regions.ts
Braintree is paypal according to @eddiemcleanlux
=> LEB-11 add base code for leforwork whitelabel

src/regions.ts
Change kogantravel phone number as required.
=> WLT-620 Change Kogantravel phone number

package.json
Bump up version to publish new lib-region for #263
=> WLT-620 Bump version for changed kogan phone number

package.json, src/priorityPhoneNumbers.ts
When trying to open customer portal, it fails due to being unable to find priority phone numbers for this brand
=> LEB-11 add priority phone numbers to leforwork brand

package.json
Bum up the version number to publish the package for changes made in #268 .
=> WLT-679 Bump up the version number

package.json, src/index.test.ts
Publish a new version of lib-regions
=> PP-1028: Publish v4.10.51 Disable latitude, Atome HK

package.json
=> bump version v4.10.52

package.json
=> WLT-679 Bump up version number for NPM publish - dynamic tags supported brands

package.json
Bump up the version number for #282
=> WLT-679 Bump up version for supported brands change to remove scooponexperience

src/currencies.ts, src/index.test.ts
Ticket: 
https://aussiecommerce.atlassian.net/browse/PP-1096
This PR aims to enable Latitude Gem as a payment option.
=> PP-1096: Enable Latitude Gem for AUD

src/currencies.ts, src/index.test.ts
Adding Velocity payment method for new Velocity Frequent Flyer (VFF) feature
=> feat: Add velocity as allowed payment method for luxuryescapes AUD

src/regions.ts
This PR updates the `insuranceProductName` from `insurance` to `protection` for AU region in all brands.
=> CRO-1967: update the 'insurance' with 'protection'

src/currencies.ts, src/index.test.ts
Add `stripe_3ds` to `INR` and WL brands
=> Add stripe 3ds to INR + WL brands

src/priorityPhoneNumbers.ts, src/regions.ts
Got the real numbers now.
https://aussiecommerce.atlassian.net/browse/LEB-232
=> LEB-232 - Update contacts numbers for LEB

src/regions.ts
Updated India phone number.
Jira ticket:  https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-1189
=> [OPEX-1189] update india phone number

src/priorityPhoneNumbers.ts
Added priority numbers for US, GB and NZ
=> feat: add us, gb and nz priority numbers

.circleci/config.yml, README.md
=> Add auto release from CI

package.json, src/regions.ts
* Current Scoopon Travel contact number does not work and this will update the number to a working one (as same as the local one)
* Related PR: https://github.com/lux-group/svc-discovery/pull/329
=> refactor: update scoopon contact number

package.json
Bump up package version for the newly published npm version
https://www.npmjs.com/package/@luxuryescapes/lib-regions/v/5.1.2
=> Publish v5.1.2 with region specific payments support

package.json, src/regions.ts
TreatMe international phone number is not correct.
https://aussiecommerce.atlassian.net/browse/EXP-1823
=> update treatme phone international number

package.json
Updates the newly published version
=> v5.1.6 to v5.1.7

package.json, src/regions.ts
Update Spain phone number. 
Jira ticket: https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-1294
=> [OPEX-1294] update Spain phone number

package.json, src/regions.ts
Update Spain phone number.
Jira ticket: https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-1294
=> [OPEX-1294] add plus to Spain phone number

src/currencies.ts, src/index.test.ts, src/regions.ts
Adding code for le agent hub (wholesale) brand, for now is the same as business traveller
=> feat(WHOL-48): add base code for wholesale whitelabel

src/priorityPhoneNumbers.ts
Adding LE Agent Hub priority numbers
=> [LEAH-48]: add agent hub priority numbers

package.json, src/regions.ts
All numbers for agent hub point to `+61 3 7032 3441`
=> [LEAH] Update agent hub contact numbers

package.json, src/regions.ts
Added new phone number type for AU --> homepage. 
Jira ticket: https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?assignee=6188ee8b22ce49007095ee9b&selectedIssue=OPEX-1527
=> [OPEX-1527] add new phone number type

src/currencies.ts, src/index.test.ts, src/paymentMethodsByregion.ts
https://aussiecommerce.atlassian.net/browse/PP-1705
- Add stripe Payto to lib regions
=> add stripe payto

package.json, src/regions.ts
https://aussiecommerce.atlassian.net/browse/OPEX-1529
=> Add mid value contact for AU LE

package.json, src/currencies.ts, src/index.test.ts, src/priorityPhoneNumbers.ts, src/regions.ts
Add New Zealand location to agent hub
=> [LEAH-214] Add New Zealand to agent hub regions

package.json, src/regions.ts
Ticket: https://aussiecommerce.atlassian.net/browse/LOYAL-476
TODO - update svc-discovery
=> [LOYAL-476] Add LuxPlus+ NZ Priority Support Number

package.json, src/index.test.ts, src/index.ts, src/paymentMethodsByregion.ts
For payment element we enable it by region. Adding AU and NZ regions for it.
=> Enable payment element for AU and NZ

src/regions.ts
Jira: https://aussiecommerce.atlassian.net/browse/OPEX-1961
Add a region specific sales phone number for the new sales phone number for LESA
=> OPEX-1961 Remove sales flow

package.json
Forgot to update contract number from PR https://github.com/lux-group/lib-regions/pull/364
=> OPEX-1961 Remove Sales Flow Update Contract

package.json, src/priorityPhoneNumbers.ts, src/regions.ts
Swap broken phone numbers
The temporary new number is 1300 915 086
Old phones:
for tours 1300 670 243
high value 1300 701 198
=> Swap broken phone numbers

package.json, src/priorityPhoneNumbers.ts, src/regions.ts
=> Revert phones back

package.json, src/currencies.ts, src/index.test.ts
https://aussiecommerce.atlassian.net/browse/PP-2006
PP-2006 enable PayTo and Apple Pay in scoopon #372
=> PP-2006 enable PayTo and Apple Pay in scoopon

src/index.test.ts, src/index.ts
Adding special mapping to redirect traffic from certain regions:
- Denmark to Netherlands
- Norway to Italy
- Sweden to Spain.
Following issue raised here
https://luxgroup-hq.slack.com/archives/C01RD9NR30C/p1725367947408739
=> Traffic from Denmark should be redirected to Netherlands

src/currencies.ts, src/index.test.ts, src/priorityPhoneNumbers.ts, src/regions.ts
It adds the necessary config for enabling the United Kingdom region and the GBP currency to the LE Agent Hub
=> feat(LEAH-539): adds UK region and GBP currency to leagenthub

package.json
It just bumps the package version so a new version can be published
Changes were implemented in PR #387
=> chore(LEAH-539): updates package version

package.json, src/regions.ts
Update the minimum purchasable Luxury escapes AU region gift card value to AUD 100
=> [GR-3290] update min purchasable value of lux au region gift card

package.json, src/regions.ts
Set minimum purchasable gift card to 50 in AU region
=> [GR-3290] revert min purchasable value of lux au region gift card

package.json, src/regions.ts
Should add +65 to Singapore numbers.
=> [CSX-2682] add prefix to Singapore numbers

src/currencies.ts, src/index.test.ts
https://aussiecommerce.atlassian.net/browse/PP-2324
Enable wechat pay
=> enable wechat pay

package.json, src/currencies.ts, src/index.test.ts
https://aussiecommerce.atlassian.net/browse/PP-2322
Added PayNow on Stripe
=> PP-2322 Stripe PayNow

src/currencies.ts, src/index.test.ts
https://aussiecommerce.atlassian.net/browse/PP-2324
- Test wechat pay on china instead of Hongkong until stripe advises us on what to do
=> test wechat pay in china region

package.json, src/insurance.ts
On https://github.com/lux-group/lib-regions/pull/403 I added CFMR enabled regions config.
But I forgot to include SG and I'm doing it now.
=> CRO-4754: Include SG in CFMR enabled regions

package.json, src/phoneNumberValidation.test.ts, src/phoneNumberValidation.ts
https://aussiecommerce.atlassian.net/browse/OPEX-3065
Add FJ to the list of available phone number regions.
=> [OPEX-3065] Add FJ to available phone number list

.github/PULL_REQUEST_TEMPLATE.md, package.json, src/currencies.ts, src/index.test.ts
Add GrabPay to SG, bump version to 5.6.59
=> PP 2624 add grab pay

package.json, src/regions.ts
Jira: https://aussiecommerce.atlassian.net/browse/TOUR-3023
This change is to add a tours priority support contact to support high value tours such as private jet tours.
Reps using the library would be now able to access the tours priority contact number based on the region selected.
Adds region-wise tours priority contact number.
NA,
Adds a constant and updates the types enum.
Have you:
NO
* name
* email
* address
* DOB
* phone number
* Passport number
=> TOUR-3023: Add tours priority phone
