__mocks__/currency-data.js
currency-data.js
index.js
index.test.js
package.json
region-data.js

As a side effect, payment methods for currencies now live in a separate list so we don't have to repeat the payment methods for regions that use the same currency.

Add function to get payment methods by currency

---

__mocks__/currency-data.js
currency-data.js
index.test.js

Since we're now exclusively using Braintree for PayPal, I figure we shouldn't have obsolete references to PayPal hanging around confusing everyone.

Remove references to PayPal payment method, replaced by Braintree

---

index.js

Blows up when calling `toLowerCase()` on null or undefined

Sometimes null or undefined is passed in

---

__mocks__/currency-data.js
__mocks__/region-data.js
currency-data.js
index.js
index.test.js
package.json
region-data.js
yarn.lock

Look up regions and currencies by brand
Default brand to luxuryescapes
Might also be useful to split out the metadata? No point in repeating...
```
code: 'AU',
name: 'Australia',
lang: 'en-AU',
currency_formatting_locale: 'en-AU',
currency_code: 'AUD',
```
Nothing else is repeated though

feat: add brand awareness

---

region-data.js

Context: We put in place this change to make mobile apps use the 13.. number. However this caused flow-on issues.

revert intl region number

---

currency-data.js
region-data.js

Do we need to differentiate between the scoopontravel and scooponexperiences brands?
Could that have just been scoopon?
If not I guess I'll change this to cudotravel and cudoexperiences..

add cudo regions

---

__mocks__/region-data.js
index.test.js
package.json
region-data.js

Adding latitude threshold info here, next step will be to update svc-discovery to use the latest version of the lib-regions so mobile can receive latitude payment details.

[LBO-1095] Add latitude info to mobile config

---

yarn.lock

An internal dependency was unpublished by the author, and that was generating an error while running the `yarn install` command
https://github.com/yarnpkg/yarn/issues/6690

fix-dependency-version

---

currency-data.js
package.json

Added support for paypal/braintree for NZ Treat Me. Also incremented version number to `3.2.1`.
This has no impact on LE.

Ee 1206 enabling braintree for treatme

---

README.md
camel.test.js
index.js
index.test.js
package.json
yarn.lock

This adds the following:
```js
var libRegions = require('@luxuryescapes/lib-regions')
libRegions.setCamel()
```
This will return everything as camel case so that you can migrate off the snake case. After people have changed we can remove this and change all the keys to camel in the data itself.

camel case migration

---

package.json
src/regions.ts

Related to https://aussiecommerce.atlassian.net/browse/LEE-157
Add settings for **Popular** label calculation for the rest of the countries. After enabling this reporting service should start calculating popularity for all countries.

[LEE-157] Enable isPopular calculation for the rest countries besides Au

---

src/index.test.ts
src/index.ts

Using a currency to find a region.
Doing this so that we can reverse lookup from a currency to a region for the credits journey.
When reverse lookup is done on **EUR** the result is always **FR** the marketing team are happy with this as a user will still be able to see their credits.

reverse lookup by currency

---

src/currencies.ts
src/index.test.ts

Lets rename the bridger_pay to bridgerpay to avoid underscore unnecessarily

rename payment provider from bridger_pay to bridgerpay to avoid extra underscore

---

src/currencies.ts
src/index.test.ts

Added support for 'applepay' for AUD for the following epic:
https://aussiecommerce.atlassian.net/browse/PP-221

Enable 'applepay' for AUD

---

src/currencies.ts
src/index.test.ts

enable google pay and or apple pay for different currencies wherever applicable.
References:
https://support.apple.com/en-us/HT207957
https://support.google.com/pay/india/answer/9023773?hl=en#zippy=%2Cpay-online-or-in-apps%2Cbuy-google-products%2Cpay-using-info-saved-to-chrome

enable apple pay and or google pay whereever applicable

---

package.json
src/currencies.ts

Story for reference:
https://aussiecommerce.atlassian.net/browse/PP-272
We need to introduce Klarna as a payment option for USD, NZD and GBP. This is being done via bridgerpay. We have introduced a new payment option 'klarna_bp' for this purpose.
The new changes have been published with version 4.8.3

PP 272 Enable klarna_bp for USD GBP NZD

---

package.json
src/currencies.ts

Klarna was turned off in https://github.com/lux-group/lib-regions/pull/186
This is for releasing the blackout of apple pay and google pay in unsupported regions in: https://github.com/lux-group/lib-regions/pull/185
Original PR: https://github.com/lux-group/lib-regions/pull/184

Turn back klarna

---

src/currencies.ts

Need to change from bridgerpay to afterpay_bp . we dont have to support bridgerpay here as this is noty live on NZD currency

Added afterpay_bp for nz

---

src/regions.ts

From https://luxgroup-hq.slack.com/archives/CFJDMH4HZ/p1640036469248400?thread_ts=1639455499.205600&cid=CFJDMH4HZ
> Turns out that many of the numbers wont be ported over for a while (with a possibility of some regions or brands having dead numbers by end of December). So to remove this risk, can we make the following updates:
> Region or brand,	Change to:
> CN,	+61291678207
> ES,	+61291678207
> YIDU,	+61370323480
> CA, +61291678207
> SG, 6690 5451
> PH,	+61291678207
> AE,	+61291678207
> ID,	+61291678207
> TH,	+61291678207
> DE,	+61291678207
> MY,	+61291678207
> NZ,	0800 900 094
> FR,	+61291678207
> Treat Me,	0800 843 182

Update various phone numbers

---

package.json
src/currencies.ts
src/index.test.ts

Adding a deposit_stripe payment option in all luxury escapes regions where stripe option available.
Tested locally
Story Number: PP-348

Added deposite_stripe payment option in luxuryescapes all regions

---

package.json
src/currencies.ts

Adding stripe_3ds to list of payment methods valid for NZD currency as part of Stripe 3DS release across NZD

Add stripe_3ds as payment method for NZD

---

package.json
src/currencies.ts

This PR adds payment type stripe3DS for GB.
npm publish details:

Enable stripe3ds for GBP

---

package.json
src/currencies.ts
src/index.test.ts

PR to enable 3DS Stripe payment option for USD, AUD and SGD currencies

Enable stripe 3DS USD AUD SGD

---

package.json
src/currencies.ts

Enables 3DS for all currencies which use stripe

v4.10.8 enable 3DS for all currencies using stripe

---

package.json
src/index.test.ts
src/regions.ts

There was a request to change default region from AU to US when it cannot be determined/not supported.
"Any idea why I'd be seeing AUD on the mobile website if I'm not logged in and my IP is in Istanbul?
If it's because we don't transact in TKL, can we change the default to USD for out of Aussie country and non-LE-covered IP address?"

DEVX-78: changing default region from AU to US for luxuryEscapes.

---

package.json
src/currencies.ts
src/index.test.ts

https://aussiecommerce.atlassian.net/browse/WLT-214
added stripe_3ds for 4 below WL brands
cudotravel → AUD
dealstravel → AUD
treatmetravel → NZD
scoopontravel → AUD

WLT-214: added stripe_3ds for 4 WL brands

---

package.json
src/regions.ts

[Ticket](https://aussiecommerce.atlassian.net/browse/OPEX-686?focusedCommentId=112137&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-112137)
Update Germany Sales & Support number from +61 2 9167 8207 → 0800 001 0786
Update [TreatMe](https://treatme.co.nz/nz) phone numbers as follows:
* Sales & Support 0800 846 182
* International Support Centre +61 3 7032 3413

OPEX-686 update germany and treatme numbers

---

README.md
package.json

Basically if you bump the version in package.json in your initial PR and follow the rest of the readme you will always bump the version by 2. I've had this happen a few times so I'm changing the readme.

Update readme and current version

---

src/index.test.ts
src/index.ts

getPaymentMethodsByCurrencyCode function is failing when brand is asked to return all payment method for currency it doesn't have

MP-1386 fix getPaymentMethodsByCurrencyCode

---

src/regions.ts

The following changes are implemented:
1. Add [20, 50, 100, 250, 500, 1000] gift card options for WL sites
2. Unrelated change: Add urgency tags to WLs for the best seller tag to start showing up on the websites.
P.S: As is required, a version bump PR will soon follow this PR.

WLT-416 Add Gift card option for Whitelabelled sites

---

src/currencies.ts
src/index.test.ts

Some WLs like Scoopontravel and Kogantravel have Latitude as payment method. This is not yet supported and should not be part of the config.

WLT-612 Remove latitude pay from WLs

---

src/currencies.ts
src/index.test.ts

https://aussiecommerce.atlassian.net/browse/PP-969
We're disabling Latitude Pay because they're closing their business.
More details in the ticket.

PP-969: Disable Latitude Pay for all portals

---

package.json

This new version was published to remove Latitude Pay as a a payment option from all portals.
This is due to Latitude Pay closing their business.
More details in ticket:
https://aussiecommerce.atlassian.net/browse/PP-969

Bump up to version 4.10.47

---

src/dynamicTags.ts
src/index.test.ts
src/index.ts
tsconfig.json

For dynamic tags to be validated, it is essential to get a list of dynamic tags that can be added to any content. In order to do so, I have added an enum defining the various tags that will be supported currently. This will help us to validate in offer service, whether the dynamic tag added by Content editors is valid/invalid. We would avoid pitfalls with typos and ensure production does not see these dynamic tags appearing without being replaced due to silly mistakes.
More on Dynamic tags - read [ADR](https://aussiecommerce.atlassian.net/wiki/spaces/TEC/pages/2459992149/2023-02+-+Allow+dynamic+tags+in+offer+content+fields+and+replace+tag+with+brand+specific+data+before+showing+to+End+User.)

WLT-679 Get valid dynamic tags 

---

src/priorityPhoneNumbers.ts

This number will be used as default, for the cases where it is not tour, cruise, ultralux or expensive packages offer.
Previous number was reassigned to ultralux.

[OPEX-928] update base support priority number

---

src/dynamicTags.ts
src/index.test.ts
src/index.ts

This is in context of dynamic tags. In order to address a [review comment](https://github.com/lux-group/svc-offer/pull/1175#discussion_r1155410287) added in Offer service PR, where we declared a constant to store the brands that support dynamic tags. Instead of using constants in offer service and public offer service, we must fetch the brands that support dynamic tags from lib-regions by using the newly added function `getValidBrandsForDynamicTags`. 
This will be used during dynamic tag replacement in Offer and public offer service.
Test case has been added for the function.

WLT-679 Add a function to get supported brands for dynamic tags. 

---

src/dynamicTags.ts

Remove `scooponexperience` from dynamic tags brand list as it is not a brand that supports dynamic tags. Scoopontravel is already in the list.

WLT-679 Remove `scooponexperience` from dynamic tags brand list

---

src/dynamicTags.ts
src/index.ts

[EXP-1510](https://aussiecommerce.atlassian.net/browse/EXP-1510)
[lib-global](https://github.com/lux-group/lib-global/pull/92)
Just add deprecation for dynamic tags logics because it was moved to lib-global.
For more information, please check the [lib-global PR](https://github.com/lux-group/lib-global/pull/92).
The intention is to remove this logic from here once svc-offer and svc-public-offer start using the lib-global.
[EXP-1510]: https://aussiecommerce.atlassian.net/browse/EXP-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EXP-1510: add deprecation for all logics about dynamic tags

---

package.json
src/currencies.ts

as you can see, with this latest version, paypal doesn't come up

LEB-327 remove braintree from list of payment providers for lebussinestraveller

---

package.json
src/currencies.ts
src/index.test.ts

A new payment methods has been made available for LE in AUD (go cardless, AKA PayTo), this PR adds that new method.

Add go cardless payment method for AUD and LE

---

src/index.test.ts
src/index.ts

Jira: https://aussiecommerce.atlassian.net/browse/CRO-27888
Figma: N/A
Implement region listing to begin with business key regions.
The new method `getRegionCodesSortedByKeyRegions` returns sorted region codes by business key regions.
eg: ["AU", "US", "GB", "NZ", "SG", ...]
It's the same rule already presented on CP:

[CRO-2788] Sort offer list regions by business key regions

---

package.json
src/currencies.ts
src/index.test.ts

We want to migrate FE code to point to stripe v2 in the BE. This has to be done in a phased manner so that changes are not deployed for all the regions overnight especially because some of the regions still has instalments feature ongoing (pending instalments). Currently we will go with EUR

Add stripe v2

---

README.md
package.json
src/currencies.ts
src/index.test.ts

[PP-1787](https://aussiecommerce.atlassian.net/browse/PP-1787)
Enable StripeV2 widget to Asia Region/Continental
[PP-1787]: https://aussiecommerce.atlassian.net/browse/PP-1787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PP-1855 enable stripe v2 in asia

---

package.json
src/currencies.ts
src/index.test.ts

We are ending the partnership with Club Vistara and the company itself no longer exists as it was aquired by Air India. This means we want to remove references to it across the stack.
This PR removes the references in lib-regions

[CRO-4035] Remove club vistara

---

.circleci/config.yml
package.json

Currently we need to fully publish the lib-region package so we can test it out end to end with CP on Staging or Canary. 
the publish require PR approval and sometime takes a while to get approved. 
I'm adding pre-publish/beta release `manual` step on pull request so dev can test lib region change end to end on staging/canary and speedup development process. 
https://github.com/lux-group/www-le-customer/pull/21526
**Circle CI**
**NPM View Output**
```
➜  ~ npm view @luxuryescapes/lib-regions         
@luxuryescapes/lib-regions@5.6.20 | UNLICENSED | deps: none | versions: 160
Region information for Luxury Escapes
https://github.com/brandsExclusive/lib-regions#readme
dist
.tarball: https://registry.npmjs.org/@luxuryescapes/lib-regions/-/lib-regions-5.6.20.tgz
.shasum: …
```

publish beta version step on PR

---

package.json
src/currencies.ts
src/index.test.ts

Ticket: https://aussiecommerce.atlassian.net/browse/PP-2089
Enable stripe element for EU regions. It's a base work for to enable iDEAL payment method for Netherlands (NL).
Note: `Beta` version is tested on Customer Portal
https://github.com/lux-group/www-le-customer/pull/21553
https://www.loom.com/share/6e81302ac6754faea5537d0e9acbbc88
https://www.loom.com/share/0290a84d64224b3599093dd59a7d7169
https://www.loom.com/share/ffba218564224f7faf4de950593c679e
https://www.loom.com/share/de8cc30cd80a440d8f48c9a1d75d5223
https://www.loom.com/share/b51b8a3090a04bfbb4896b45b14f0d24
https://www.loom.com/share/c8c9ba41ec264499898891d93ad08782
https://www.loom.com/share/864e65906d3d4b07a83e718a93557cf9

PP-2089 EU stripe element v2

---

package.json
src/index.test.ts
src/paymentMethodsByregion.ts

1. Add support for new payment type - flying blue. This type is enabled only for France and Netherlands 
2. Remove other supported payment types from choosing based on region as the currency 'EUR' supports others for NL.

add flying blue support

---

package.json
src/index.test.ts
src/index.ts
src/regions.ts

https://aussiecommerce.atlassian.net/browse/OPERX-151
CP PR: https://github.com/lux-group/www-le-customer/pull/22641
The cancellation retention modal needs to be updated such that it can display the correct phone number depending on the region of the order the customer is trying to cancel.
To achieve this, `lib-regions` needs to be updated to hold information about the cancellation retention phone numbers for regions where this is supported. This PR adds the cancellation retention phone number for the following regions:
- AU (this is hardcoded into CP currently but will be refactored to use the value declared in this lib)
- NZ
- US
- GB
The values defined here will be consumed by CP and will be shown in the cancellation retention modal.

[OPERX-151] Add cancellation retention phone numbers for several regions

---

package.json
src/index.test.ts
src/index.ts

JIRA: https://aussiecommerce.atlassian.net/browse/CRO-4583
We want to move up Hong Kong and Taiwan regions on the curation list selection:
This method is only used by admin: https://github.com/search?q=org%3Alux-group%20getRegionCodesSortedByKeyRegions&type=code
Unit tests was updated

[CRO-4583]: Include Hong Kong and Taiwan into admin priority list

---

package.json
src/currencies.ts
src/index.test.ts

Azupay is a new payment provider and we intend to use the PayId payment method of their's in Au region.
This PR adds the payment method to Au region for luxury escapes brand.

add azupay to Aus region

---

package.json
src/index.ts
src/insurance.ts

The countries where CFMR (Cancel for Many Reasons) is enabled differ from those for insurance.
This PR adds the CFMR-enabled countries so they can be used across different projects (currently CP and svc-insurance).

CRO-4754: Include CFMR enabled origin countries

---

package.json
src/index.ts
src/phoneNumberValidation.test.ts
src/phoneNumberValidation.ts
yarn.lock

https://aussiecommerce.atlassian.net/browse/OPEX-3004
We want to improve how phone numbers are validated. The existing implementation doesn't scale too well as we are defining a regex for each region that needs to be supported by LE.
In response to this limitation, this PR does the following:
- Consume a lightweight 3rd party package to assist in validating phone numbers by region
- This will improve maintenance effort in the long run as we don't have to maintain our own regex patterns for each region that needs to be supported by LE
- Create a new `isPhoneNumberValidForRegion` function which will serve as the centralised function where phone numbers are validated by region
- Maintain a separate list of regions we want to support phone numbers for
- Current list only supports specific …

[OPEX-3004] Improved phone number validation

---

package.json
src/phoneNumberValidation.test.ts
src/phoneNumberValidation.ts

https://aussiecommerce.atlassian.net/browse/OPEX-3044
Sometimes, the library just isn't good enough.
So lets give the ability to override it with our own validation regex.

[OPEX-3044] Phone number validation regex override

---

package.json
src/index.test.ts
src/index.ts

Jira: https://aussiecommerce.atlassian.net/jira/software/projects/CRO/boards/114?selectedIssue=CRO-5055
Why these changes are needed:
- We are starting to invest more marketing effort in growing South Africa, Qatar and Malaysia
- We need to add South Africa, Malaysia, and Qatar to this top section (below Taiwan, above the hr)

[CRO 5055] Updated region start order

---

package.json
src/currencies.ts

Jira: https://aussiecommerce.atlassian.net/browse/PP-2639
We want to allow Malaysia customers to purchase via GrabPay
Added GrabPay to paymentMethods

PP-2639 GrabPay in Malaysia
